- name: Install jitsi videobridge
  apt:
    name:
      - "jitsi-videobridge2"
    update_cache: true
    state: present

- name: Reconfigure Jitsi Video-Bridge
  template:
    src: "jitsi/videobridge/{{ item }}.j2"
    dest: "/etc/jitsi/videobridge/{{ item }}"
  notify: restart jitsi-videobridge2
  with_items:
    - "config"

- name: Deploy videobridge.rc
  template:
    src: "jitsi/videobridge/videobridge.rc.j2"
    dest: "/usr/share/jitsi-videobridge/lib/videobridge.rc mit"
  notify: restart jitsi-videobridge2
