- name: Install prosody jwt auth deps
  apt:
    name:
      - "git"
      - "cmake"
      - "luarocks"
      - "libssl-dev"
      - "liblua5.2-0"
    state: present

- name: Deploy luajwtjitsi.rockspec
  template:
    src: "prosody/luajwtjitsi.rockspec.j2"
    dest: "/tmp/luajwtjitsi.rockspec"

- name: Install lua-basexx
  shell: "luarocks install basexx"
  args:
    creates: "/usr/local/share/lua/5.2/basexx.lua"

- name: Install luajwtjitsi
  shell: "luarocks install /tmp/luajwtjitsi.rockspec"
  args:
    creates: "/usr/local/share/lua/5.2/luajwtjitsi.lua"

- name: Deploy patched mod_websocket.lua and mod_token_verification
  template:
    src: "prosody/{{ item }}.j2"
    dest: "/usr/lib/prosody/modules/{{ item }}"
  with_items:
    - mod_websocket.lua
    - mod_token_moderation.lua

- name: Download additional prosody modules from jitsi
  get_url:
    url: "https://raw.githubusercontent.com/jitsi/jitsi-meet/master/resources/prosody-plugins/{{ item }}.lua"
    dest: "/usr/lib/prosody/modules/{{ item }}.lua"
    mode: "0644"
  with_items:
    - mod_auth_token
    - mod_token_verification
    - mod_presence_identity
